<?php
$current = $this->getCurrentLink();
$editor = $this->getAdmin()->getWhiteLabelEditor();
$request = $this->getRequest();
$session = $this->getSession();
$supportLink = __get('support_link');
if (Nwicode::$whitelabel) {
    $supportLink = Nwicode::$whitelabel->getSupportLink();
}

if (empty($supportLink)) {
    $supportLink = false;
}

// Awesome menu
$editorTree = [
    'dashboard' => [
        'hasChilds' => false,
        'isVisible' => $this->isPe(),
        'label' => __('Dashboard'),
        'id' => 'sb-tour-dashboard',
        'is_current' => 'app_list' === $current,
        'url' => $this->getUrl('/'),
        'icon' => 'fa fa-tachometer',
    ],
    //'push_global' => [
    //    'hasChilds' => false,
    //    'isVisible' => $this->_canAccess('push_admin_global'),
    //    'label' => __('Push notifications'),
    //    'id' => 'sb-tour-global-push',
    //    'is_current' => 'push_global' === $current,
    //    'url' => $this->getUrl('push/admin/global'),
    //    'icon' => 'fa fa-bullhorn',
    //],
    'whitelabel' => [
        'hasChilds' => true,
        'isVisible' => ($this->isPe() && $this->_canAccessWhiteLabelEditor()),
        'label' => __('White Label'),
        'id' => 'sb-tour-whitelabel',
        'icon' => 'fa fa-tags',
        'childs' => [
            'settings' => [
                'hasChilds' => false,
                'isVisible' => true,
                'label' => __('Settings'),
                'url' => $this->getUrl('whitelabel/editor/index'),
                'is_current' => 'white_label_editor' === $current,
            ],
            'activity' => [
                'hasChilds' => false,
                'isVisible' => true,
                'label' => __('Activity'),
                'url' => $this->getUrl('whitelabel/editor/activity'),
                'is_current' => 'white_label_activity' === $current,
            ],
        ],
        'is_current' => in_array($current, ['white_label_activity', 'white_label_editor']),
    ],
    'profile' => [
        'hasChilds' => true,
        'isVisible' => true,
        'label' => __('My account'),
        'id' => 'sb-tour-profile',
        'icon' => 'fa fa-user',
        'childs' => [
            'access_management' => [
                'hasChilds' => false,
                'isVisible' => !$request->isWhiteLabelEditor() && $this->_canAccess('admin_access_management'),
                'label' => __('Users'),
                'url' => $this->getUrl('admin/access_management/list'),
                'is_current' => 'access_management' === $current,
            ],
            'subscriptions' => [
                'hasChilds' => false,
                'isVisible' => !$request->isWhiteLabelEditor() && $this->_canAccessSubscription(),
                'label' => __('Subscriptions'),
                'url' => $this->getUrl('sales/admin_subscription/list'),
                'is_current' => 'my_subscriptions' === $current,
            ],
            'invoices' => [
                'hasChilds' => false,
                'isVisible' => !$request->isWhiteLabelEditor() && $this->_canAccessInvoice(),
                'label' => __('Invoices'),
                'url' => $this->getUrl('sales/admin_invoice/list'),
                'is_current' => 'my_invoices' === $current,
            ],
            'manage_tour' => [
                'hasChilds' => false,
                'isVisible' => $session->getAdmin()->isAllowedToManageTour(),
                'label' => __('Manage tour'),
                'extra' => 'onclick="sbTour.switchTourEdition()"',
                'is_current' => false,
            ],
            'profile_divider' => [
                'isVisible' => true,
                'divider' => true,
                'is_current' => false,
            ],
            'my_account' => [
                'hasChilds' => false,
                'isVisible' => true,
                'label' => __('Profile'),
                'url' => $this->getUrl('admin/account/edit'),
                'is_current' => 'my_account' === $current,
            ],
            'profile_divider_2' => [
                'isVisible' => true,
                'divider' => true,
                'is_current' => false,
            ],
            'logout' => [
                'hasChilds' => false,
                'isVisible' => true,
                'label' => __('Log-out'),
                'url' => $this->getUrl('admin/account/logout'),
                'is_current' => false,
            ],
        ],
        'is_current' => in_array($current, ['my_invoices', 'my_subscriptions', 'access_management', 'my_account']),
    ],
    'support_link' => [
        'hasChilds' => false,
        'isVisible' => $this->_canAccess('support') && $supportLink,
        'label' => __('Support'),
        'id' => 'sb-tour-support',
        'url' => $supportLink,
        'icon' => 'fa fa-medkit',
    ],
];

$editorTree = \Nwicode\Hook::trigger('editor.header.menu.ready', $editorTree);

/**
 * @param $markup
 * @param $menus
 * @param int $level
 * @return string
 */
function renderRecursive($markup, $menus, $isChild = false) {
    foreach ($menus as $menu) {
        if (!$menu['isVisible']) {
            continue;
        }

        // Simple divider!
        if (array_key_exists('divider', $menu)) {
            $markup .= '
                <li role="separator"
                    class="divider">
                </li>';
        } else if ($menu['hasChilds']) {
            $childs = '<ul class="dropdown-menu content-white-bkg">' .
                renderRecursive('', $menu['childs'], true) . '</ul>';

            if (!$isChild) {
                $label = '
                <div class="section-responsive">
                    ' . $menu['label'] . ' <span class="caret"></span>
                </div>';
            } else {
                $label = $menu['label'];
            }
            $isCurrent = $menu['is_current'] ? 'is_current' : '-';
            $markup .= '
                <li class="dropdown languages ' . $isCurrent . '">
                    <a id="' . $menu['id'] . '"
                       href="#"
                       data-toggle="dropdown" 
                       role="button" 
                       class="box foo sb-tour"
                       aria-haspopup="true" 
                       aria-expanded="false"
                       title="' . $menu['label'] . '">
                        <i class="' . $menu['icon'] . '"></i>
                        ' . $label . '
                    </a>
                    ' . $childs . '
                </li>';
        } else {

            if (!$isChild) {
                $label = '
                <div class="section-responsive">
                    ' . $menu['label'] . '
                </div>';
            } else {
                $label = $menu['label'];
            }

            $extra = '';
            if (array_key_exists('extra', $menu)) {
                $extra = $menu['extra'];
            }

            $isCurrent = $menu['is_current'] ? 'is_current' : '-';
            $markup .= '
                <li class="' . $isCurrent . '">
                    <a id="' . $menu['id'] . '"
                       href="' . $menu['url'] . '"
                       ' . $extra . '
                       title="' . $menu['label'] . '">
                        <i class="' . $menu['icon'] . '"></i>
                        ' . $label . '
                    </a>
                </li>';
        }
    }
    return $markup;
}

$outputHtml = renderRecursive('', $editorTree);

// Development warning!
$isDevelopment = (APPLICATION_ENV !== 'production');
?>

<div id="customization_label"
     class="mode color-blue"
     style="display:none;">
    <span class="color-blue"
          style="top:-100px;">
        <p style="text-transform:uppercase"><?php echo __('Customization mode activated'); ?></p>
    </span>
</div>
<nav class="navbar navbar-default content-white-bkg" id="nav-header-id">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <?php $platform_name = (Nwicode::$whitelabel) ? '' : __get('platform_name'); ?>
        <a id="sb-tour-logo-platform"
           href="<?php echo $this->getUrl('admin/application/list'); ?>"
           class="sb-tour pull-left logo-position">
            <img src="<?php echo $this->getLogo(); ?>"
                 id="logo"
                 alt="<?php echo $platform_name; ?>"
                 title="<?php echo $platform_name; ?>"
                 width="100%" />
        </a>
    </div>
    <button type="button" id="menu-toggler" style="transition: all 0.5s ease 0s;" class="navbar-toggle collapsed content-white-bkg" onclick="toggleMenu()" data-toggle="tooltip" data-placement="right" title="a+s">
       <i class="icon ion-arrow-swap" style="position: relative;top: -6px;"></i>
    </button>
    <div class="collapse navbar-collapse" id="bs-navbar">
        <?php if (__get('bootstraptour_active') == "1"): ?>
            <button id="sb-tour-enable"
                    class="sb-tour pull-right btn color-blue"
                    onclick="launchBootstrapTour()">
                <i class="fa fa-question-circle-o"
                   style="font-size: 25px;"></i>
            </button>
        <?php endif; ?>
        <ul class="nav navbar-nav navbar-right">
            <?php if ($this->isSae()) : ?>
                <li class="-">
                    <a href="/backoffice" target="_blank" class="box foo sb-tour" title="<?php echo __('Backoffice'); ?>">
                        <i class="fa fa-desktop"></i>    
                        <div class="section-responsive">
                        <?php echo __('Backoffice'); ?>
                        </div>
                    </a>
                </li>
            <?php endif; ?>
            <?php if (System_Model_Config::getValueFor('enable_doforme_button') == '1'): ?>
            <li class="-">
                <a data-toggle="modal" data-target=".bs-example-modal-sm" class="box foo sb-tour" title="<?php echo __('Make for me'); ?>">
                    <i class="fa fa-handshake-o"></i>    
                    <div class="section-responsive">
                    <?php echo __('Make for me'); ?>
                    </div>
                </a>
            </li>
            <?php endif; ?>
            <?php echo $outputHtml; ?>

            <?php echo $this->getPartialHtml('languages'); ?>
            
            <?php if ($this->isPe() && !$request->isWhiteLabelEditor()) : ?>
                <li class="-">
                    <a onclick="wl_editor.toggle();" class="box foo sb-tour" title="<?php echo __('Customize My Editor'); ?>">
                        <i class="fa fa-desktop"></i>    
                        <div class="section-responsive">
                        <?php echo __('Customize My Editor'); ?>
                        </div>
                    </a>
                </li>
            <?php endif; ?>
        </ul>
    </div>
</nav>

<!-- Окно формы заявки "Сделай за меня" -->
<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 style="text-align:center;" class="modal-title" id="mySmallModalLabel"><?php echo __('Make for me'); ?></h4>
            </div>
            <div class="modal-body">
                <form id="sendmakeforme" action="<?php echo $this->getUrl('admin/account/sendmakeforme'); ?>" method="post">
                    <input name="email" type="hidden" value="<?php echo $adminemail; ?>"/>
                    <div class="form-group">
                        <label for="subject"><?php echo __('Message subject'); ?></label>	  
                        <input name="subject" type="text" class="sb-tour input-flat" placeholder="<?php echo __('Message subject'); ?>" required/> 
                    </div>
                    <div class="form-group">
                        <label for="message"><?php echo __('Message'); ?></label>
                        <textarea name="message" class="sb-tour input-flat" placeholder="<?php echo __('Message'); ?>" required></textarea>
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-info" value="<?php echo __('Send'); ?>" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- Окно формы заявки "Сделай за меня" -->

<?php if ($isDevelopment): ?>
    <div class="alert alert-warning development-responsive small-dev">
        <div class="big">
            <i class="fa fa-exclamation-triangle"></i>
            <span>
                <?php echo __('You current working environment is'); ?>&nbsp;
            </span>
            <b><?php echo __('Development') ?></b>, <?php echo __('be careful or set it back to') ?>
            <b><?php echo __('Production') ?></b>
            <span class="dismiss-dev">
                <i class="fa fa-times"></i> <b><?php echo __('REDUCE') ?></b>
            </span>
        </div>
        <div class="small">
            <i class="fa fa-exclamation-triangle"></i>
            <span>
                <?php echo __('Environment is'); ?>&nbsp;
            </span>
            <b><?php echo __('Development') ?></b>
        </div>
    </div>
<?php endif; ?>

<style>
    #nav-header-id {
        transition: all 0.5s ease 0s;
        -moz-transition: all 0.5s ease 0s;
        -webkit-transition: all 0.5s ease 0s;
        -o-transition: all 0.5s ease 0s;
    }
    .togglegnav {
        padding-left: 0px !important;
        transition: all 0.5s ease 0s;
        -moz-transition: all 0.5s ease 0s;
        -webkit-transition: all 0.5s ease 0s;
        -o-transition: all 0.5s ease 0s;
    }
    .togglegnavnoleft {
        padding-left: 0px !important;
        -webkit-transition: none !important;
        transition: none !important;
        -moz-transition: none !important;
        -o-transition: none !important;
    }
    #toggle_customization_sidebar {
        height: 50px;
        margin-top: 4px;
    }

    @media (min-width: 960px) {
        #toggle_customization_sidebar.visible {
            display: block
        }

        #toggle_customization_sidebar {
        }
    }

    .development-responsive .small {
        display: none;
    }

    .development-responsive.small-dev .big {
        display: none !important;
    }

    .development-responsive.small-dev .small {
        display: block !important;
    }

    .development-responsive .dismiss-dev {
        position: absolute;
        right: 20px;
        cursor: pointer;
    }

    .development-responsive.small-dev {
        width: 250px;
        border-right: 2px solid #8a6d3b !important;
    }

    .development-responsive.small-dev {

    }

    #sb-tour-enable {
        height: 50px;
        margin-top: 10px;
        margin-left: 10px;
        width: 50px;
    }
</style>

<script src="https://unpkg.com/hotkeys-js/dist/hotkeys.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#menu-toggler').tooltip()
        var dismissDev = $('.dismiss-dev');

        dismissDev.off('click');
        dismissDev.on('click', function () {
            $('.development-responsive').addClass('small-dev');
            localStorage.setItem('small-dev', true);
        });

        if (!localStorage.getItem('small-dev')) {
            $('.development-responsive').removeClass('small-dev');
        }

        //Отправка формы "сделать за меня"
        $('#sendmakeforme').submit(function() {
            if($(this).valid()) {
                reload(this, this.action, true);
            }
            return false;
        });
        //Отправка формы "сделать за меня"

        //Определение MAC OS или Windows
        function isMacintosh() {
            return navigator.platform.indexOf('Mac') > -1
        }

        function isWindows() {
            return navigator.platform.indexOf('Win') > -1
        }

        var isMac = isMacintosh();
        var isPC = isWindows();

        if(isMac) {
            //Управление горячими клавишами https://wangchujiang.com/hotkeys/
            hotkeys('a+s', function (event, handler){
                switch (handler.key) {
                    case 'a+s': toggleMenu();
                    break;
                }
            });
            //Управление горячими клавишами
        } else {
            //Управление горячими клавишами https://wangchujiang.com/hotkeys/
            hotkeys('a+s', function (event, handler){
                switch (handler.key) {
                    case 'a+s': toggleMenu();
                    break;
                }
            });
            //Управление горячими клавишами
        }
        //Определение MAC OS или Windows
    });
</script>