<?php
/**
 * Class WebView_Form_WebView
 */
class WebView_Form_WebView extends Nwicode_Form_Abstract
{
    /**
     * @throws Zend_Form_Exception
     */
    public function init()
    {
        parent::init();

        $this
            ->setAction(__path('/webview/application/editpost'))
            ->setAttrib('id', 'form-webview');

        // Bind as a create form!
        self::addClass('create', $this);

        $webviewUrl = $this->addSimpleText(
            'url',
            __('Enter the URL'),
            'http://...',
            true);
        $webviewUrl
            ->setRequired(true);
        
        /**$webviewBannerText = $this->addSimpleText('banner_text', __('Enter the Banner Text'));**/

        $icon = $this->addSimpleImage('icon', __('Logo'), __('Logo'),
            [
                'width' => 512,
                'height' => 512,
            ]
        );

        $webviewloadingSpinnerDelay = $this->addSimpleText(
            'loading_spinner_delay',
            __('Loading Spinner Delay (seconds)'),
            '1',
            true);
        $webviewloadingSpinnerDelay
            ->setRequired(true);

        $value_id = $this->addSimpleHidden('value_id');
        $value_id
            ->setRequired(true);

        $this->addSubmit(__('Save'));
    }

    /**
     * Override isValid to add special rules
     *
     * @param array $data
     * @return bool
     * @throws Zend_Form_Exception
     */
    public function isValid($data)
    {
        if ($data['is_qr_ean']) {
            $this
                ->getElement('query_string')
                ->setRequired(true);
             $this
                ->getElement('banner_text')
                ->setRequired(true);    
        }

        return parent::isValid($data); // TODO: Change the autogenerated stub
    }

}