<?php
$pushForm = new Push_Form_Global();
$columns = 'col-lg-12';
$application = Application_Model_Application::getInstance();
$devices = $application->getDevices();
$isPublished = false;
foreach ($devices as $device) {
	if ($device->getStatusId() === '3') {
		$isPublished = true;
		break;
	}
}
$pushForm->removeElement('send_to_all');
?>

<div class="page-content-wrapper content solo-page">
    <h3 class="title-editor border-blue text-center"><?php echo __("Global push notifications"); ?></h3>
    <div class="subcontent content-color container-fluid">
        <div class="row">
            <div id="sb-tour-global-push-1" class="<?php echo $columns; ?> sb-tour">
                <?php if (!$isPublished): ?>
                    <div class="alert alert-info">
                        <?php echo __("In order to use global push notifications your app must be published.") ?>
                    </div>
                <?php endif; ?>
                <h4 class="center"><?php echo __("Push notification"); ?></h4>
                <div id="push-form-bind" class="subcontent content-color">
                    <?php echo $pushForm; ?>
                </div>
                <div style="clear:both"></div>
            </div>
        </div>
    </div>
</div>


<style type="text/css">
    div.fix-pos {
        margin: 0 !important;
    }
</style>

<script type="text/javascript">
    $(document).ready(function() {

        bindForms("#push-form-bind", "color-blue", function(data) {
            $("#form-push-global").get(0).reset();
            $("#send_to_all").prop("checked", false).trigger("change");
        });

        var url_content = $("#url").parents(".sb-form-line");

        url_content.hide();

        $("#open_url").on("change", function(element) {

            if($("#open_url").prop("checked")) {
                url_content.show();
            } else {
                url_content.hide();
            }

        });

        $("#send_to_all").on("change", function(element) {

            if($("#send_to_all").prop("checked")) {
                $("input.appid-checkbox").prop("checked", true);
            } else {
                $("input.appid-checkbox").prop("checked", false);
            }

        });

        $("input.appid-checkbox").on("change", function() {
            var total = $("input.appid-checkbox").length;
            var checked = $("input.appid-checkbox:checked").length;

            if(total === checked) {
                $("#send_to_all").prop('checked', true);
                $("#checked").val('');
            } else {
                $("#send_to_all").prop('checked', false);

                var checked = [];
                $("input.appid-checkbox:checked").each(function (index, element) {
                    checked.push($(element).data('appid'));
                });
                $("#checked").val(checked.join(','));
            }
        });

        $('table.sb-pager')
            .sbpager({
                items_per_page: 10,
                with_search: true,
                search_placeholder: "<?php echo __("Search, filter ...") ?>",
                callback_goto_page: function() {}
            });

    });
</script>