<div class="animated part part1 title-margin">
    <h3 class="title blue10">Nwicode CMS нужно немного информации о вашем сервере баз данных.</h3>
    <p>Пожалуйста, заполните эту форму.</p>
</div>
<div class="animated part part2">
    <form id="databaseForm">
        <table class="no-collapse" cellspacing="10" width="100%">
            <tr>
                <td><input type="text" id="db_host" name="host" class="required input-flat" placeholder="Хост" /></td>
                <td><input type="text" id="db_name" name="dbname" class="required input-flat" placeholder="Имя базы данных" /></td>
            </tr>
            <tr>
                <td><input type="text" id="db_username" name="username" class="required input-flat" placeholder="Имя пользователя БД" /></td>
                <td><input type="password" id="db_password" name="password" class="required input-flat" placeholder="Пароль БД" /></td>
            </tr>
        </table>
        <button type="submit" style="display:none;"></button>
    </form>
    <div>
        <p id="checking_connection" class="checking_connection_status loading" style="display:none;">Проверка соединения</p>
        <p id="connection_is_ok" class="checking_connection_status blue5" style="display:none;"><i class="icon-ok"></i> Ваше подключение к базе данных установлено правильно!</p>
        <p id="connection_has_failed" class="checking_connection_status red5" style="display:none;"></p>
    </div>
</div>
<script type="text/javascript">
    var step = new Step(3);
    $('#databaseForm').submit(function() {
        installer.nextStep();
        return false;
    });
    step.canGoForward = function() {
        if($('#databaseForm').valid()) {
            return installer.checkDatabaseConnection();
        }
        return false;
    };
    installer.addStep(step);
</script>