<?php echo $this->doctype() ?>
<html>
    <head>
        <title><?php echo __($this->getTitle()) ?></title>
        <?php foreach($this->getMetas() as $meta) : ?>
        <meta <?php echo $meta->getTag() ?>="<?php echo $meta->getKey(); ?>" content="<?php echo __($meta->getContent()); ?>" />
        <?php endforeach ?>

        <?php foreach(Core_Model_Language::getLanguages() as $language) : ?>
        <?php if(Core_Model_Language::getCurrentLanguage() == $language->getCode()) continue;?>
        <link rel="alternate" href="<?php echo $this->getCurrentUrl(true, $language->getCode()); ?>" hreflang="<?php echo $language->getCode() ?>" />
        <?php endforeach ?>

        <?php echo $this->headLink() ?>

        <link rel="icon" type="image/png" href="/favicon.png" />
        <link rel="shortcut icon" id="favicon" type="image/x-icon" href="/favicon.ico" />
        <?php $base_url = str_replace($this->getRequest()->getPathInfo(), "", $this->getRequest()->getRequestUri()); ?>
        <?php if(stripos($base_url, "/") !== 0) $base_url = "/$base_url"; ?>
        <base href="<?php echo $base_url; ?>" />



        <?php echo Nwicode_Debug::renderHead(); ?>
    </head>
    <body class="<?php echo $this->default_class_name ?> general">
        <div ng-app="Nwicode-Backoffice">
        <?php echo $this->getPartialHtml('mainmenu') ?>
        <div  id="backoffice-main-window" >
        
            <?php if (APPLICATION_ENV !== 'production'): ?>
                <div class="alert alert-warning development-responsive">
                    <i class="fa fa-exclamation-triangle"></i>
                    <span>
                        <?php echo __('You current working environment is'); ?>&nbsp;
                    </span>
                    <b><?php echo __('Development') ?></b>, <?php echo __('be careful or set it back to') ?>&nbsp;
                    <a href="/backoffice/advanced_configuration">
                        <i class="fa fa-external-link"></i>
                        <b><?php echo __('Production') ?></b>
                    </a>
                </div>
            <?php endif; ?>
            
            <!--<div class="top">
                <?php /*echo $this->getPartialHtml('header')*/ ?>
                <div class="message slide-down"
                     ng-show="message.is_visible"
                     ng-class="{error: message.is_error}">
                    <p ng-bind-html="message.text"></p>
                </div>
            </div>-->
            <div class="message slide-down alert alert-danger nwicode-message"
                ng-show="message.is_visible && message.is_error"
                role="alert"
                ng-bind-html="message.text">
            </div>
            <div class="message slide-down alert alert-success nwicode-message"
                ng-show="message.is_visible && !message.is_error"
                ng-bind-html="message.text"
                role="alert">
            </div>                    
            <?php echo $this->getPartialHtml('messages') ?>
            <?php echo $this->getPartialHtml('menu'); ?>
            <div>
                <div id="wrapper"
                     class="background"
                     ng-class="direction">
                    <div ng-view class="slide-view background"
                         ng-class="code"
                         ng-if="isLoggedIn"></div>
                    <sb-login-dialog class="scale-fade background"
                                     ng-if="!isLoggedIn"></sb-login-dialog>
                </div>

                <?php echo $this->getPartialHtml("templates"); ?>
            </div>

            <div class="footer">
                <?php echo $this->getPartialHtml('footer') ?>
            </div>

            <script type="text/ng-template" id="loginForm.html">
                <?php echo $this->getPartialHtml("login"); ?>
            </script>
        </div>
        <?php echo $this->headScript() ?>
    </div>
        
        <script type="text/javascript">
            var BASE_URL = "<?php echo $base_url == "/" ? "" : $base_url; ?>";
            var ORIG_URL = "<?php echo $this->getRequest()->getRequestUri(); ?>";
            if(ORIG_URL.indexOf('/') !== 0) ORIG_URL = '/'+ORIG_URL;
            var IMAGE_PATH = "<?php echo $this->getImagePath(); ?>";
            App.factory("Label", function(Message) {
                var factory = {};

                factory.loading = {
                    success: "",
                    error: "<?php echo $this->_("An error occurred while loading. Please, try again later."); ?>"
                };

                factory.save = {
                    success: "<?php echo $this->_("Info successfully saved"); ?>",
                    error: "<?php echo $this->_("An error occurred while saving. Please try again later."); ?>"
                };

                factory.uploader = {
                    error: {
                        type: {
                            zip: "<?php echo $this->_("You can upload a zip archive only."); ?>",
                            pem: "<?php echo $this->_("You can upload a pem certificate only."); ?>",
                            image: "<?php echo $this->_("You can upload an image only (.jpg, .jpeg, .gif and .png)."); ?>",
                            icon: "<?php echo $this->_("You can upload an icon only (.ico and .png)."); ?>",
                            png: "<?php echo $this->_("You can upload a png only (.png)."); ?>"
                        },
                        only_one_at_a_time: "<?php echo addslashes($this->_("You can't upload more than one file at a time.")); ?>",
                        general: "<?php echo addslashes($this->_("An error occurred while uploading your file. Please, try again later.")); ?>"
                    }
                };

                factory.android = {
                    generating_apk: "<?php echo $this->_("Your APK is being generated. Please come back in a few minutes."); ?>"
                };

                factory.admin = {
                    confirm_deletion: "<?php echo $this->_("Are you sure you want to delete this admin?"); ?>"
                }

                return factory;
            });

            App.run(function($rootScope, AUTH_EVENTS, Auth) {
                Auth.user.id = "<?php echo $this->getSession()->getBackofficeUserId(); ?>";
                $rootScope.$broadcast(AUTH_EVENTS.loginSuccess);
                console.log("Page app start event.");
                console.log(Auth.user.id);
                $rootScope.$on(AUTH_EVENTS.notAuthenticated, function() { console.log("event: AUTH_EVENTS.notAuthenticated"); });
                $rootScope.$on(AUTH_EVENTS.logoutSuccess, function() { console.log("event: AUTH_EVENTS.logoutSuccess");  $( '#nwicode-menu' ).css("display","none");});
                $rootScope.$on(AUTH_EVENTS.loginSuccess, function() { console.log("event: AUTH_EVENTS.loginSuccess"); $( '#nwicode-menu' ).css("display","block");});
                if (Auth.user.id!="") setTimeout(() => show_menu(false), 1000); else setTimeout(() => show_menu(true), 1000); 
                //setTimeout(show_menu, 2000);
            })



        </script>
        
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js"></script>
<script type="text/javascript" src="/app/sae/design/desktop/backoffice/js/fisheye-iutil.min.js"></script>
<script type="text/javascript" src="/app/sae/design/desktop/backoffice/js/jquery.jqDock.min.js"></script>
<script type="text/javascript" src="/app/sae/design/desktop/backoffice/js/stack-1.js"></script>
<script type="text/javascript" src="/app/sae/design/desktop/backoffice/js/jquery.multilevelpushmenu.min.js"></script>
<script type="text/javascript" src="//oss.maxcdn.com/libs/modernizr/2.6.2/modernizr.min.js"></script>
<script type="text/javascript">

function show_menu(hide) {
    console.log("do show menu");
    $( '#nwicode-menu' ).css("display","block"); 
    $( '#nwicode-menu' ).multilevelpushmenu({
        containersToPush: [$( '#backoffice-main-window' )],
        collapsed: false,
        menuHeight: "100%",
        menuWidth: '300px',
        backText: '<?php echo $this->_("Back"); ?>',
        onItemClick: function() {
            // First argument is original event object
            var event = arguments[0],
                // Second argument is menu level object containing clicked item (<div> element)
                $menuLevelHolder = arguments[1],
                // Third argument is clicked item (<li> element)
                $item = arguments[2],
                // Fourth argument is instance settings/options object
                options = arguments[3];

            // You can do some cool stuff here before
            // redirecting to href location
            // like logging the event or even
            // adding some parameters to href, etc...

            // Anchor href
            var itemHref = $item.find( 'a:first' ).attr( 'href' );
            var item_id = $item.find( 'a:first' ).attr( 'id' );
            // Redirecting the page
            if (item_id!="logout-href") location.href = itemHref;
        },
        onCollapseMenuEnd: function() {

            
        }  
    });
    if (hide) $( '#nwicode-menu' ).css("display","none");    
}

var pageHeight = $(document).height();
//menu redraw timer
setInterval(() => {
    var new_pageHeight = $(document).height();
    if (new_pageHeight>pageHeight) {
        $( '#nwicode-menu_multilevelpushmenu' ).css('height', new_pageHeight+'px'); console.log('redraw '+new_pageHeight+'px');
        pageHeight = new_pageHeight;
    }
}, 100);

</script>

</body>
</html>
