<div>
    <ul class="list-group">
        <li class="animated step1 list-group-item"><i id="step1_ok" class="icon-ok blue5 animated" style="opacity:0;"></i> Добро пожаловать!</li>
        <li class="animated step2 list-group-item"><i id="step2_ok" class="icon-ok blue5 animated" style="opacity:0;"></i> Соглашение</li>
        <li class="animated step3 list-group-item"><i id="step3_ok" class="icon-ok blue5 animated" style="opacity:0;"></i> БД</li>
        <li class="animated step4 list-group-item"><i id="step4_ok" class="icon-ok blue5 animated" style="opacity:0;"></i> Установка</li>
        <li class="animated step5 list-group-item"><i id="step5_ok" class="icon-ok blue5 animated" style="opacity:0;"></i> Админ</li>
        <li class="animated step6 list-group-item"><i id="step6_ok" class="icon-ok blue5 animated" style="opacity:0;"></i> Приложение</li>
        <li class="animated step7 list-group-item"><i id="step7_ok" class="icon-ok blue5 animated" style="opacity:0;"></i> Готово!</li>
    </ul>
</div>
