<div class="title">
    <div class="title_content">
        <button id="previous_step" class="blue5 opacity_on_active left"><i class="icon-angle-left"></i></button>
            <h1 class="animated step step1 blue5 f-rounded">Добро пожаловать в Nwicode CMS</h1>
            <h1 class="animated step step2 blue5 f-rounded">Соглашение</h1>
            <h1 class="animated step step3 blue5 f-rounded">БД</h1>
            <h1 class="animated step step4 blue5 f-rounded">Установка</h1>
            <h1 class="animated step step5 blue5 f-rounded">Админ</h1>
            <h1 class="animated step step6 blue5 f-rounded">Приложение</h1>
            <h1 class="animated step step7 blue5 f-rounded">Готово!</h1>
        <button id="next_step" class="blue5 opacity_on_active right"><i class="icon-angle-right"></i></button>
    </div>
</div>