<?php 

	//Получим данные кошелька
	//$application = $this->getApplication();
	if ($this->getSession()->getAppId()) $app_id = $this->getSession()->getAppId(); else $app_id=$this->getApplication()->getId();
	$db =Zend_Db_Table_Abstract::getDefaultAdapter();

	$recommend_version = "2.7.8";
	$stmt = $db->query(
		'SELECT version FROM module WHERE name = ?',
		array('Wallet')
	);
	$current_version =$stmt->fetch()['version'];
	

	if (empty($current_version)) {
		echo "Wallet module not found! Exit...";
		?><br><a href="<?php echo (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://$_SERVER[HTTP_HOST]";?>" rel="" class="navigation"><i class="fa fa-sign-out fa-lg"></i> <?php echo __('Exit to Editor'); ?></a><br><?php
		die(__("Wallet module not found! Exit..."));
	}	
	
	$stmt = $db->query(
		'SELECT * FROM application_option WHERE code = ?',
		array('wallet')
	);
	$option_id = $stmt->fetch()['option_id'];
	$stmt = $db->query(
		'SELECT * FROM application_option_value WHERE option_id = ? and app_id = ?',
		array($option_id, $app_id)
	);
	$value_id = $stmt->fetch()['value_id'];

	$wallet = new Wallet_Model_Wallet();
	$wallet->find(array("value_id" => $value_id));
	

	$addfundshistory = $wallet->getAddFundsHsitory();
	
	//Подготовим графики 
	$date_counter2 = [];    //Массив с датами
	//предзаполнинм нулевыми данными месяц
	$date_period = new DatePeriod((new DateTime('NOW'))->modify('-30 days'), new DateInterval('P1D'), (new DateTime('NOW'))->modify('+1 day'));				
	foreach ($date_period as $key => $value) $date_counter2[$value->format('Y-m-d')]=0;
	
	//Запросим все транзакции
	$transactions = $wallet->getAddFundsHsitory();
	foreach ($transactions as $tr) if ($tr->getComplete()) {
		$dt = (new DateTime($tr->getCreatedAt()))->format('Y-m-d');
		if (isset($date_counter2[$dt])) $date_counter2[$dt]=$date_counter2[$dt]+(float)abs($tr->getSumm());
	}
	
?>

<div id="list-panel">
<div class="row">
	<div class="col-sm-12">
		<h1><?php echo __('History of add funds'); ?></h1>
	</div>
</div>

<!-- charts-->

<div class="panel panel-default">
  <div class="panel-heading">
	<h3 class="panel-title"><?php echo __("Last 30 days transactions");?></h3>
  </div>
  <div class="panel-body" id="chartdiv2">
  </div>
</div>	

<table id="addfundshistory" class="table table-striped table-bordered" style="width:100%">
        <thead>
		  <tr>
			<th><?php echo __("Date");?></th>
			<th><?php echo __("Amount");?></th>
			<th><?php echo __("Description");?> </th>
			<th><?php echo __("Status");?> </th>
		  </tr>
        </thead>
		<tbody>
			<?php foreach($addfundshistory as $tr) {?>
			<?php
			
			?>
            <tr>
			<td><?php echo $tr->getCreatedAt();?></td>
			<td><?php echo abs($tr->getSumm());?></td>
			<td><?php echo $tr->getCode();?> </td>
			<td>
				<?php 
					if ($tr->getComplete()==-1) echo __("Canceled");
					if ($tr->getComplete()==0) echo __("Pending");
					if ($tr->getComplete()==1) echo __("OK");
				?>
			</td>
            </tr>
			<?php } ?>
		</tbody>
        <tfoot>
            <tr>
			<th><?php echo __("Date");?></th>
			<th><?php echo __("Amount");?></th>
			<th><?php echo __("Description");?> </th>
			<th><?php echo __("Status");?> </th>
            </tr>
        </tfoot>
    </table>
</div>
<div id="item-panel">

</div>

<div id="item-subpanel">

</div>

<script type="text/javascript">



$(document).ready(function() {
    var addfundshistory = $('#addfundshistory').DataTable(

		{
			"pagingType": "full_numbers",
			language: {
				paginate: {
					first:    '«',
					previous: '‹',
					next:     '›',
					last:     '»'
				},
				aria: {
					paginate: {
						first:    '<?php echo __('First'); ?>',
						previous: '<?php echo __('Previous'); ?>',
						next:     '<?php echo __('Next'); ?>',
						last:     '<?php echo __('Last'); ?>'
					}
				},
				"emptyTable": "<?php echo __('No data available in table'); ?>",
				"info": "<?php echo __('Showing page _PAGE_ of _PAGES_'); ?>",
				"infoEmpty": "<?php echo __('No entries to show'); ?>",
				"search": "<?php echo __('Search'); ?>"
			}
		}	
		
	);
	addfundshistory.column( '0:visible' ).order( 'desc' ).draw(); 
	addfundshistory.columns().flatten().each( function ( colIdx ) {
		
		if (colIdx==2 || colIdx==3 ) {
			console.log(colIdx);
			// Create the select list and search operation
			var select = $('<select><option value=""></option></select>')
				.appendTo(
					addfundshistory.column(colIdx).footer()
				)
				.on( 'change', function () {
					addfundshistory
						.column( colIdx )
						.search( $(this).val() )
						.draw();
				} );
		 
			// Get the search data for the first column and add to the select list
			addfundshistory
				.column( colIdx )
				.cache( 'search' )
				.sort()
				.unique()
				.each( function ( d ) {
					select.append( $('<option value="'+d+'">'+d+'</option>') );
				} );
			
		}	
	} );	
	
} );
</script>

<!-- Styles -->
<style>
#chartdiv2 {
  width: 100%;
  height: 300px;
}
</style>


<!-- Charts code -->
<script>
am4core.ready(function() {

	// Themes begin
	am4core.useTheme(am4themes_material);
	am4core.useTheme(am4themes_animated);
	// Themes end
	
	// Create chart instance
	var chart2 = am4core.create("chartdiv2", am4charts.XYChart);

	// Add data
	<?php $tmp_array = array(); foreach ($date_counter2 as $date=>$value) $tmp_array[]='{"date":"'.$date.'","amount":'.$value.'}'; ?>
	chart2.data = [<?php echo implode(",",$tmp_array);?>];

	var dateAxes2 = chart2.xAxes.push(new am4charts.CategoryAxis());
	dateAxes2.dataFields.category = "date";
	dateAxes2.title.text = "<?php echo __("Date"); ?>";
	
	
	var valueAxis2 = chart2.yAxes.push(new am4charts.ValueAxis());
	valueAxis2.title.text = "<?php echo __("Amount"); ?>";
	valueAxis2.dataFields.category = "amount";
	
	// Create series
	var series2 = chart2.series.push(new am4charts.ColumnSeries());
	series2.dataFields.valueY = "amount";
	series2.dataFields.categoryX = "date";
	series2.name = "<?php echo __("Amount"); ?>";
	series2.columns.template.tooltipText = "{categoryX}: [bold]{valueY}[/]";
	series2.columns.template.fillOpacity = .8;

	var columnTemplate2 = series2.columns.template;
	columnTemplate2.strokeWidth = 2;
	columnTemplate2.strokeOpacity = 1;	

}); // end am4core.ready()

</script>
