<?php 

	//Получим данные кошелька
	//$application = $this->getApplication();
	if ($this->getSession()->getAppId()) $app_id = $this->getSession()->getAppId(); else $app_id=$this->getApplication()->getId();
	$db =Zend_Db_Table_Abstract::getDefaultAdapter();

	$recommend_version = "2.7.8";
	$stmt = $db->query(
		'SELECT version FROM module WHERE name = ?',
		array('Wallet')
	);
	$current_version =$stmt->fetch()['version'];
	

	if (empty($current_version)) {
		echo "Wallet module not found! Exit...";
		?><br><a href="<?php echo (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://$_SERVER[HTTP_HOST]";?>" rel="" class="navigation"><i class="fa fa-sign-out fa-lg"></i> <?php echo __('Exit to Editor'); ?></a><br><?php
		die(__("Wallet module not found! Exit..."));
	}	
	
	$stmt = $db->query(
		'SELECT * FROM application_option WHERE code = ?',
		array('wallet')
	);
	$option_id = $stmt->fetch()['option_id'];
	$stmt = $db->query(
		'SELECT * FROM application_option_value WHERE option_id = ? and app_id = ?',
		array($option_id, $app_id)
	);
	$value_id = $stmt->fetch()['value_id'];

	$wallet = new Wallet_Model_Wallet();
	$wallet->find(array("value_id" => $value_id));
	
	$requests = $wallet->getPayoutRequests();
	
?>

<div id="list-panel">
<div class="row">
	<div class="col-sm-12">
		<h1><?php echo __('Payout requests'); ?></h1>
	</div>
</div>

<table id="requests" class="table table-striped table-bordered  table-condensed" style="width:100%">
        <thead>
		  <tr>
			<th><?php echo __("Date");?></th>
			<th><?php echo __("Method");?></th>
			<th><?php echo __("Amount");?></th>
			<th><?php echo __("Customer");?></th>
			<th><?php echo __("Comment");?></th>
			<th><?php echo __("Status");?></th>
			<th><?php echo __("Reply");?></th>
			<th><em class="fa fa-cog"></em></th>
		  </tr>
        </thead>
		<tbody>
		<?php foreach($requests as $request) { ?>
			<tr id="row-request-<?php echo $request->getId();?>">
			<td class="request-created"><?php echo $request->getData('created_at');?></td>
			<td class="request-method"><?php echo $request->getData('payout_method_title');?></td>
			<td class="request-amount"><?php echo $request->getData('summ');?></td>
			<td class="request-customer"><?php echo $request->getCustomer()->getData('email');?></td>
			<td class="request-comment"><?php echo $request->getData('customer_info');?></td>
			<td class="request-status"><?php echo $request->getData('status');?></td>
			<td class="request-reply"><?php echo $request->getData('admin_info');?></td>

			<td><a class="btn btn-default" onclick="openRequest(<?php echo $request->getId();?>);"><em class="fa fa-eye"></em></a></td>
			</tr>
		<?php } ?>
		</tbody>
        <tfoot>
		  <tr>
			<th><?php echo __("Date");?></th>
			<th><?php echo __("Method");?></th>
			<th><?php echo __("Amount");?></th>
			<th><?php echo __("Customer");?></th>
			<th><?php echo __("Comment");?></th>
			<th><?php echo __("Status");?></th>
			<th><?php echo __("Reply");?></th>
			<th><em class="fa fa-cog"></em></th>
		  </tr>
        </tfoot>
    </table>
</div>
<div id="item-panel">

</div>

<div id="item-subpanel">

</div>
<script type="text/javascript">

function openRequest(id) {
	loader_show();
	var url = '<?php echo $this->getUrl('wallet/admin/request'); ?>';
	$.ajax({
	   url:url,
	   type:'POST',
	   data: "wallet_payout_request_id="+id,
	   dataType: "json",
	   cache: false,
	   success: function(data){
			console.log(data);
		   $('#list-panel').hide();
		   $("#success-message").hide();
		   $("#error-message").hide();		   
		   $('#item-panel').html(data.html).show();
		   $("html, body").animate({ scrollTop: 0 }, "fast");
		   loader_hide();
		   
	   }
	});	

}

$(document).ready(function() {
    var table_requests = $('#requests').DataTable(
		{
			"pagingType": "full_numbers",
			language: {
				paginate: {
					first:    '«',
					previous: '‹',
					next:     '›',
					last:     '»'
				},
				aria: {
					paginate: {
						first:    '<?php echo __('First'); ?>',
						previous: '<?php echo __('Previous'); ?>',
						next:     '<?php echo __('Next'); ?>',
						last:     '<?php echo __('Last'); ?>'
					}
				},
				"emptyTable": "<?php echo __('No data available in table'); ?>",
				"info": "<?php echo __('Showing page _PAGE_ of _PAGES_'); ?>",
				"infoEmpty": "<?php echo __('No entries to show'); ?>",
				"search": "<?php echo __('Search'); ?>"
				
			}
		}	
	
	);
	table_requests.column( '0:visible' ).order( 'desc' ).draw(); 
	table_requests.columns().flatten().each( function ( colIdx ) {
		
		if (colIdx==1 || colIdx==3 || colIdx==5) {
			console.log(colIdx);
			// Create the select list and search operation
			var select = $('<select><option value=""></option></select>')
				.appendTo(
					table_requests.column(colIdx).footer()
				)
				.on( 'change', function () {
					table_requests
						.column( colIdx )
						.search( $(this).val() )
						.draw();
				} );
		 
			// Get the search data for the first column and add to the select list
			table_requests
				.column( colIdx )
				.cache( 'search' )
				.sort()
				.unique()
				.each( function ( d ) {
					select.append( $('<option value="'+d+'">'+d+'</option>') );
				} );
			
		}	
	} );	
	
} );
</script>