<?php 

	//Получим данные кошелька
	//$application = $this->getApplication();
	if ($this->getSession()->getAppId()) $app_id = $this->getSession()->getAppId(); else $app_id=$this->getApplication()->getId();
	$db =Zend_Db_Table_Abstract::getDefaultAdapter();

	$recommend_version = "2.7.8";
	$stmt = $db->query(
		'SELECT version FROM module WHERE name = ?',
		array('Wallet')
	);
	$current_version =$stmt->fetch()['version'];
	

	if (empty($current_version)) {
		echo "Wallet module not found! Exit...";
		?><br><a href="<?php echo (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://$_SERVER[HTTP_HOST]";?>" rel="" class="navigation"><i class="fa fa-sign-out fa-lg"></i> <?php echo __('Exit to Editor'); ?></a><br><?php
		die(__("Wallet module not found! Exit..."));
	}	
	
	$stmt = $db->query(
		'SELECT * FROM application_option WHERE code = ?',
		array('wallet')
	);
	$option_id = $stmt->fetch()['option_id'];
	$stmt = $db->query(
		'SELECT * FROM application_option_value WHERE option_id = ? and app_id = ?',
		array($option_id, $app_id)
	);
	$value_id = $stmt->fetch()['value_id'];

	$wallet = new Wallet_Model_Wallet();
	$wallet->find(array("value_id" => $value_id));
	

	$transactions = $wallet->getTransactions();
	
	//Подготовим графики 
	$date_counter1 = [];    //Массив с датами
	//предзаполнинм нулевыми данными месяц
	$date_period = new DatePeriod((new DateTime('NOW'))->modify('-1 month'), new DateInterval('P1D'), (new DateTime('NOW'))->modify('+1 day'));				
	foreach ($date_period as $key => $value) $date_counter1[$value->format('Y-m-d')]=0;
	
	//Запросим все транзакции
	$transactions2 = (new Wallet_Model_Wallet())->getTransactionsLimit(array("wallet_id = ?"=>$wallet->getId(), "type"=>"in", "created_at > ?"=>(new DateTime('NOW'))->modify('-1 month')->format('Y-m-d')));
	foreach ($transactions2 as $tr) {
		$dt = (new DateTime($tr->getCreatedAt()))->format('Y-m-d');
		if (isset($date_counter1[$dt])) $date_counter1[$dt]=$date_counter1[$dt]+(float)abs($tr->getOperationSumm());
	}	
	
?>

<div id="list-panel">
<div class="row">
	<div class="col-sm-12">
		<h1><?php echo __('Transactions'); ?></h1>
	</div>
</div>

<!-- charts-->

<div class="panel panel-default">
  <div class="panel-heading">
	<h3 class="panel-title"><?php echo __("Last 30 fund upload");?></h3>
  </div>
  <div class="panel-body" id="chartdiv1">
  </div>
</div>	


<table id="transactions" class="table table-striped table-bordered table-condensed" style="width:100%">
        <thead>
		  <tr>
			<th><?php echo __("Date");?></th>
			<th><?php echo __("Amount");?></th>
			<th><?php echo __("From account");?></th>
			<th><?php echo __("To account");?></th>
			<th><?php echo __("Description");?> </th>
		  </tr>
        </thead>
		<tbody>
			<?php foreach($transactions as $tr) if ($tr->getOsTransactionId()==0){?>
			<?php
			
				$account1 = "-";
				$account1 = (new Wallet_Model_Customer())->find($tr->getWalletCustomerId())->getEmail();
		
				$account2 = "-";
				if ($tr->getToCustomerId()!=0) {
					$to_account = (new Wallet_Model_Customer())->find($tr->getToCustomerId());
					if ($to_account->getId()) $account2 = $to_account->getEmail();
				}			
			
			?>
            <tr>
			<td><?php echo $tr->getCreatedAt();?></td>
			<td><?php echo abs($tr->getOperationSumm());?></td>
			<td><?php echo $account1;?></td>
			<td><?php echo $account2;?></td>
			<td><?php echo $tr->getDescription();?><br><?php echo $tr->getTransactionNote();?></td>
            </tr>
			<?php } ?>
		</tbody>
        <tfoot>
            <tr>
			<th><?php echo __("Date");?></th>
			<th><?php echo __("Amount");?></th>
			<th><?php echo __("From account");?></th>
			<th><?php echo __("To account");?></th>
			<th><?php echo __("Description");?> </th>
            </tr>
        </tfoot>
    </table>
</div>
<div id="item-panel">

</div>

<div id="item-subpanel">

</div>

<script type="text/javascript">



$(document).ready(function() {
    var transactions = $('#transactions').DataTable(
		{
			"pagingType": "full_numbers",
			language: {
				paginate: {
					first:    '«',
					previous: '‹',
					next:     '›',
					last:     '»'
				},
				aria: {
					paginate: {
						first:    '<?php echo __('First'); ?>',
						previous: '<?php echo __('Previous'); ?>',
						next:     '<?php echo __('Next'); ?>',
						last:     '<?php echo __('Last'); ?>'
					}
				},
				"emptyTable": "<?php echo __('No data available in table'); ?>",
				"info": "<?php echo __('Showing page _PAGE_ of _PAGES_'); ?>",
				"infoEmpty": "<?php echo __('No entries to show'); ?>",
				"search": "<?php echo __('Search'); ?>"
				
			}
		}	
	
	);
	transactions.column( '0:visible' ).order( 'desc' ).draw(); 
	transactions.columns().flatten().each( function ( colIdx ) {
		
		if (colIdx==2 || colIdx==3 ) {
			console.log(colIdx);
			// Create the select list and search operation
			var select = $('<select><option value=""></option></select>')
				.appendTo(
					transactions.column(colIdx).footer()
				)
				.on( 'change', function () {
					transactions
						.column( colIdx )
						.search( $(this).val() )
						.draw();
				} );
		 
			// Get the search data for the first column and add to the select list
			transactions
				.column( colIdx )
				.cache( 'search' )
				.sort()
				.unique()
				.each( function ( d ) {
					select.append( $('<option value="'+d+'">'+d+'</option>') );
				} );
			
		}	
	} );	
	
} );
</script>
<!-- Styles -->
<style>
#chartdiv1 {
  width: 100%;
  height: 300px;
}

</style>
<!-- Charts code -->
<script>
am4core.ready(function() {

	// Themes begin
	am4core.useTheme(am4themes_material);
	am4core.useTheme(am4themes_animated);
	// Themes end

	// Create chart instance
	var chart1 = am4core.create("chartdiv1", am4charts.XYChart);

	// Add data
	<?php $tmp_array = array(); foreach ($date_counter1 as $date=>$value) $tmp_array[]='{"date":"'.$date.'","amount":'.$value.'}'; ?>
	chart1.data = [<?php echo implode(",",$tmp_array);?>];

	var dateAxes = chart1.xAxes.push(new am4charts.CategoryAxis());
	dateAxes.dataFields.category = "date";
	dateAxes.title.text = "<?php echo __("Date"); ?>";
	
	
	var valueAxis = chart1.yAxes.push(new am4charts.ValueAxis());
	valueAxis.title.text = "<?php echo __("Amount"); ?>";
	valueAxis.dataFields.category = "amount";
	
	// Create series
	var series = chart1.series.push(new am4charts.ColumnSeries());
	series.dataFields.valueY = "amount";
	series.dataFields.categoryX = "date";
	series.name = "<?php echo __("Amount"); ?>";
	series.columns.template.tooltipText = "{categoryX}: [bold]{valueY}[/]";
	series.columns.template.fillOpacity = .8;

	var columnTemplate = series.columns.template;
	columnTemplate.strokeWidth = 2;
	columnTemplate.strokeOpacity = 1;


}); // end am4core.ready()

</script>