<?php
/**
 * @var Application_Model_Application $application
 */
$application = $this->getApplication();
$offlineSub = $application->getOfflineSubscription();
$hasFreePlan = true;
?>

<?php if ($this->_canAccess('editor_publication') &&
    $application->canBePublished()) : ?>
<?php endif; ?>

<script type="text/javascript">
    var modal_subscribe_page = new Modal({
        id: 'modal_subscribe_page',
        url: '<?php echo $this->getUrl('application/customization_features/subscribepage'); ?>',
        is_retain: false,
        width: 850,
        height: 'auto'
    });
    $('#feature_subscribe_page').click(function () {
        modal_subscribe_page.show();
    });
</script>
<script type="text/javascript">
    <?php if (($application->subscriptionIsActive() && $application->getSubscription()) || $application->getOfflineSubscription()):
    $subscriptionApp = $application->subscriptionIsActive() ? $application->getSubscription() : $application->getOfflineSubscription();
    ?>
    var cancelUrl = '<?php echo $this->getUrl('subscription/application/cancelowner'); ?>';
    var id = '<?php echo $subscriptionApp->getId() ?>';

    $(document).ready(function () {
        var cancelButton = $('.cancel-subscription');
        cancelButton.off('click');
        cancelButton.on('click', function () {
            swal({
                html: true,
                title: '<?php echo __js("Cancel Subscription", "'") ?>',
                type: 'prompt',
                text: '<?php echo __js("You are about to cancel your Subscription, if this is a paid plan the subscription will be cancelled at the end of the recurring period, otherwise the subscription will be immediately cancelled and the application locked.<br /><br />Below you can leave a message for the Administrator.<br />", "'") ?>',
                showCancelButton: true,
                closeOnConfirm: false,
                closeOnCancel: true,
                confirmButtonColor: '#ff3a2e',
                confirmButtonText: '<?php echo __js("Yes, Cancel my subscription", "'") ?>',
                cancelButtonText: '<?php echo __js("No, go back!", "'") ?>',
                buttons: {
                    confirm: {
                        value: ''
                    }
                }
            }, function (value) {
                if (value === false) {
                    return;
                }

                formget(
                    cancelUrl,
                    {
                        'id': id,
                        'message': value
                    },
                    function (data) {
                        // Success!
                        feature_form_success(data.message);
                        setTimeout(function () {
                            location.reload();
                        }, 3000);
                    },
                    function (data) {
                        feature_form_error(data.message);
                    });

                swal.close();
                return true;
            });
        });
    });
    <?php endif; ?>
</script>
