<?php
$has_previewer = Installer_Model_Installer::hasModule("previewer");
$previewer = null;
if($has_previewer && method_exists(new Previewer_Model_Previewer(), "getInstance")) {
    $previewer = Previewer_Model_Previewer::getInstance();
}
?>
<div id="iphone" style="transition: all 0.5s ease 0s;">
    <div class="docs-demo-device md">
    	<figure>
    		<svg class="docs-demo-device__md-bar" viewBox="0 0 1384.3 40.3">
    			<path class="st0" d="M1343 5l18.8 32.3c.8 1.3 2.7 1.3 3.5 0L1384 5c.8-1.3-.2-3-1.7-3h-37.6c-1.5 0-2.5 1.7-1.7 3z"></path>
    			<circle class="st0" cx="1299" cy="20.2" r="20"></circle>
    			<path class="st0" d="M1213 1.2h30c2.2 0 4 1.8 4 4v30c0 2.2-1.8 4-4 4h-30c-2.2 0-4-1.8-4-4v-30c0-2.3 1.8-4 4-4zM16 4.2h64c8.8 0 16 7.2 16 16s-7.2 16-16 16H16c-8.8 0-16-7.2-16-16s7.2-16 16-16z"></path>
    		</svg>
    		<svg class="docs-demo-device__ios-notch" viewBox="0 0 219 31">
    			<path d="M0 1V0h219v1a5 5 0 0 0-5 5v3c0 12.15-9.85 22-22 22H27C14.85 31 5 21.15 5 9V6a5 5 0 0 0-5-5z" fill-rule="evenodd"></path>
    		</svg>
    		<iframe id="mobile_overview" sandbox="allow-same-origin allow-scripts allow-forms allow-modals" width="324" height="579" style="overflow: hidden; background-color: lightgrey;"></iframe>
    	</figure>
    </div>
</div>
<style>
.docs-demo-mode-toggle button.is-selected {
    background-color: var(--text-color--dark);
    color: white;
}
.docs-demo-mode-toggle button {
    background-color: transparent;
    border: none;
    border-radius: 16px;
    color: var(--text-color--light);
    cursor: pointer;
    font-size: 10px;
    font-weight: 700;
    letter-spacing: 0.1em;
    line-height: 24px;
    margin: 0px 3px;
    padding: 0 9px;
    text-transform: uppercase;
    -webkit-transition: 200ms background-color ease, 200ms color ease;
    transition: 200ms background-color ease, 200ms color ease;
}
.docs-demo-mode-toggle {
    -ms-flex-align: center;
    align-items: center;
    display: -ms-flexbox;
    display: flex;
    -ms-flex-pack: center;
    justify-content: center;
    padding-top: 1rem;
}
    .docs-demo-device {
    --device-aspect-ratio: 2.125;
    --device-padding: 2rem;
    padding: var(--device-padding);
    position: -webkit-sticky;
    position: sticky;
    top: 0;
}
.docs-demo-device > figure {
    border-radius: 32px;
    -webkit-box-shadow: 0 0 0 14px #090a0d, 0 0 0 17px #9fa3a8, 0 0 34px 17px rgba(0,0,0,0.2);
    box-shadow: 0 0 0 14px #090a0d, 0 0 0 17px #9fa3a8, 0 0 34px 17px rgba(0,0,0,0.2);
    height: 0;
    margin: 0;
    max-width: 320px;
    min-width: 320px;
    overflow: hidden;
    padding-bottom: calc(var(--device-aspect-ratio) * 100%);
    position: relative;
    width: calc((100vh - var(--header-height) - var(--device-padding) * 2) / var(--device-aspect-ratio));
    z-index: 1;
}
.docs-demo-device__md-bar {
    display: none;
}
.docs-demo-device {
    --device-aspect-ratio: 2.125;
    --device-padding: 2rem;
    padding: var(--device-padding);
    position: -webkit-sticky;
    position: sticky;
    top: 0;
}
.docs-demo-device.ios .docs-demo-device__ios-notch, .docs-demo-device.ios figure:after {
    display: block;
}
.docs-demo-device__ios-notch {
    display: none;
    fill: #090a0d;
    left: 50%;
    position: absolute;
    top: -1px;
    -webkit-transform: translateX(-50%);
    transform: translateX(-50%);
    width: 165px;
    z-index: 2;
}
.docs-demo-device > figure > iframe {
    border: none;
    height: 100%;
    left: 0;
    position: absolute;
    top: 0;
    width: 100%;
    z-index: 1;
}
iframe {
    background-color: rgba(0, 0, 0, 0.02);
    -webkit-box-shadow: 10px 10px 20px rgba(0,0,0,0.1);
    box-shadow: 10px 10px 20px rgba(0,0,0,0.1);
}
</style>
<script type="text/javascript">
    let overview = [];
    let buttonOverviewSize = $('button.overview_size');
    let iPhone = $('#iphone');

    let setSize = function (rel) {
        let sizes = overview[rel];
        if (sizes && !$(this).hasClass('active')) {

            let button = $('.overview_size[rel="' + rel + '"]');

            localStorage.setItem('overview_last_choice', rel);

            $('#mobile_overview').attr('width', sizes.width)
            .attr('height', sizes.height)
            ;

            $('.toolbar_overview').hide();
            if (sizes.toolbar) {
                $('#'+sizes.toolbar).show();
            }

            iPhone.css('background-image', 'url('+sizes.background+')');
            iPhone.css({
                width: sizes.container_width,
                height: sizes.container_height
            });

            $('.iphone_content').css({
                'margin-top' : sizes.marginTop,
                'margin-left': sizes.marginLeft
            });

            /** Resize mask */
            $("#mask-overview").css({
                'top' : sizes.marginTop,
                'left': sizes.marginLeft,
                'width': sizes.width,
                'height': sizes.height
            });

            try {
                if(button.attr("rel").indexOf("iphone") >= 0) {
                    iframe.content.find("body").removeClass("platform-browser").addClass("platform-ios")
                } else {
                    iframe.content.find("body").removeClass("platform-ios").addClass("platform-android")
                }
            } catch (e) {
                // Later maybe!
            }

            $('.overview_size').removeClass('active');
            button.addClass('active');
        }
    };

    buttonOverviewSize.off("click");
    buttonOverviewSize.on("click", function() {
        let rel = $(this).attr('rel');
        setSize(rel);
    });

    $(document).ready(function() {
        $("#mobile_overview").attr("src", "<?php echo $this->getApplication()->getUrl("/", [], Core_Model_Language::getCurrentLanguage(), true); ?>?overview=1");
        iframe.iframeIsLoaded = function() {
            iframe.content.find("body").removeClass("platform-browser").addClass("platform-ios");
            $("#mask-overview").hide();

            setTimeout(function() {
                if((typeof iframe != "undefined")
                    && (typeof iframe.f != "undefined")
                    && (typeof iframe.f.setPath == "function")
                    && (typeof window.overviewEvents != "undefined")
                    && (window.overviewEvents.length > 0)) {

                    iframe.contentWindow.setPath(window.overviewEvents[0]);
                    window.overviewEvents = [];
                }
            }, 1000);

        };

        let lastChoice = localStorage.getItem('overview_last_choice');
        if (lastChoice) {
            setSize(lastChoice);
        } else {
            setSize('iphone5');
        }
    });

</script>